# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/sebasala/Desktop/Work/Andrews/Subsystem_test/Subsystem_06_02/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/sebasala/Desktop/Work/Andrews/Subsystem_test/Subsystem_06_02/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.2 [current_project]
set_property ip_repo_paths {
  c:/Users/sebasala/Desktop/Work/Andrews/Subsystem_test/Subsystem_06_02/ip_repo/subsystem_1.0
  c:/Users/sebasala/Desktop/Work/Andrews/Subsystem_test/Subsystem_06_02/ip_repo/PE16_Block_1.0
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/sebasala/Desktop/Work/Andrews/Subsystem_test/Subsystem_06_02/project_1/project_1.srcs/sources_1/new/BRAM.v
  C:/Users/sebasala/Desktop/Work/Andrews/Subsystem_test/Subsystem_06_02/project_1/project_1.srcs/sources_1/new/Serialized_ALU.v
  C:/Users/sebasala/Desktop/Work/Andrews/Subsystem_test/Subsystem_06_02/project_1/project_1.srcs/sources_1/new/PE16_Block.v
  C:/Users/sebasala/Desktop/Work/Andrews/Subsystem_test/Subsystem_06_02/project_1/project_1.srcs/sources_1/new/Controller.v
  C:/Users/sebasala/Desktop/Work/Andrews/Subsystem_test/Subsystem_06_02/project_1/project_1.srcs/sources_1/new/Top.v
}
read_xdc C:/Users/sebasala/Desktop/Work/Andrews/Subsystem_test/Subsystem_06_02/project_1/project_1.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/sebasala/Desktop/Work/Andrews/Subsystem_test/Subsystem_06_02/project_1/project_1.srcs/constrs_1/new/constraints.xdc]

synth_design -top Top -part xc7vx485tffg1761-2
write_checkpoint -noxdef Top.dcp
catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
