# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/sebasala/desktop/work/andrews/splitter/ip_repo/edit_Register_File_v1_0.cache/wt [current_project]
set_property parent.project_path c:/users/sebasala/desktop/work/andrews/splitter/ip_repo/edit_Register_File_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.2 [current_project]
set_property ip_repo_paths {
  c:/Users/sebasala/Desktop/Work/Andrews/Splitter/ip_repo/Register_File_1.0
  c:/Users/sebasala/Desktop/Work/Andrews/Splitter/ip_repo/Register_File_1.0
  c:/Users/sebasala/Desktop/Work/Andrews/Splitter/ip_repo/Register_File_1.0
  c:/Users/sebasala/Desktop/Work/Andrews/Splitter/ip_repo/Decoder_1.0
  c:/Users/sebasala/Desktop/Work/Andrews/Timer_Test/ip_repo
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  c:/users/sebasala/desktop/work/andrews/splitter/ip_repo/register_file_1.0/hdl/Register_File_v1_0_S_AXI.vhd
  c:/users/sebasala/desktop/work/andrews/splitter/ip_repo/register_file_1.0/hdl/Register_File_v1_0.vhd
}
synth_design -top Register_File_v1_0 -part xc7vx485tffg1761-2
write_checkpoint -noxdef Register_File_v1_0.dcp
catch { report_utilization -file Register_File_v1_0_utilization_synth.rpt -pb Register_File_v1_0_utilization_synth.pb }
